victoire_core:
    widgets:
        Filter:
            class: "Victoire\\Widget\\FilterBundle\\Entity\\WidgetFilter"
            name: Filter

jms_translation:
    configs:
        victoire_filter_bundle:
            dirs: ["@VictoireWidgetFilterBundle"]
            output_dir: "@VictoireWidgetFilterBundle/Resources/translations"
