victoire_core:
    widgets:
        filter:
            class: "Victoire\\FilterBundle\\Entity\\WidgetFilter"
            name: filter

jms_translation:
    configs:
        victoire_filter_bundle:
            dirs: ["@VictoireFilterBundle"]
            output_dir: "@VictoireFilterBundle/Resources/translations"
