services:
    victoire_core.twig.widget_filter_manager:
        class: Victoire\Widget\FilterBundle\Widget\Manager\WidgetFilterManager
        arguments: [@service_container]

    widget_filter_manager:
        alias: victoire_core.twig.widget_filter_manager

    victoire_core.filter.form.type:
        class: Victoire\Widget\FilterBundle\Filter\FilterType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: filter }

    victoire_core.filter_chain:
        class: "Victoire\Widget\FilterBundle\Filter\Chain\FilterChain"
