services:
    victoire_core.widget_filter_content_resolver:
        class: Victoire\Widget\FilterBundle\Resolver\WidgetFilterContentResolver
        arguments:
            - @form.factory
            - @router
            - @victoire_core.current_view
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Filter }

    #alias to the entity
    victoire.widget.filter:
        class: Victoire\Widget\FilterBundle\Entity\WidgetFilter
    #alias to the form
    victoire.widget.form.filter:
        class: Victoire\Widget\FilterBundle\Form\WidgetFilterType
        arguments:
            - @event_dispatcher
        tags:
            - { name: form.type , alias: victoire_widget_form_filter}

    #alias to the form
    victoire.form.filter:
        class: Victoire\Widget\FilterBundle\Filter\FilterType
        tags:
            - { name: form.type , alias: filter}