services:
    victoire_core.filter_chain:
        class: Victoire\Widget\FilterBundle\Filter\Chain\FilterChain

    victoire_core.widget_filter_content_resolver:
        class: Victoire\Widget\FilterBundle\Resolver\WidgetFilterContentResolver
        arguments:
            - @form.factory
            - @router
            - @victoire_core.current_view
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Filter }

    #alias to the entity
    victoire.widget.filter:
        class: Victoire\Widget\FilterBundle\Entity\WidgetFilter
    #alias to the form
    victoire.widget.form.filter:
        class: Victoire\Widget\FilterBundle\Form\WidgetFilterType
        arguments:
            - @event_dispatcher
        tags:
            - { name: form.type , alias: victoire_widget_form_filter}

    #alias to the form
    victoire.form.filter:
        class: Victoire\Widget\FilterBundle\Filter\FilterType
        tags:
            - { name: form.type , alias: victoire_form_filter}

    victoire.widget_filter.form.listener.presetdata:
        class: Victoire\Widget\FilterBundle\EventListener\WidgetFilterFormEventListener
        tags:
            - { name: kernel.event_listener, event: victoire.widget_filter.form.pre_set_data, method: manageExtraFiltersFields, priority: 1 }

    victoire.widget_filter.form.listener.presubmit:
        class: Victoire\Widget\FilterBundle\EventListener\WidgetFilterFormEventListener
        tags:
            - { name: kernel.event_listener, event: victoire.widget_filter.form.pre_submit, method: manageExtraFiltersFields, priority: 1 }